# Generated by Django 5.2.5 on 2025-08-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cloths', 'Cloths'), ('bags', 'Bags'), ('footwears', 'Footwears'), ('assessories', 'Assessories')], max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
