# Generated by Django 5.2.5 on 2025-08-18 16:10

import apiconfig.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0005_order_status_order_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apiconfig.models.CustomUserManager()),
            ],
        ),
    ]
