# Generated by Django 5.2.5 on 2025-08-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
