# Generated by Django 5.2.5 on 2025-09-03 23:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0008_rename_price_at_purchase_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
