# Generated by Django 5.2.5 on 2025-09-03 23:26

import apiconfig.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0009_alter_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(default=apiconfig.models.Order.generate_reference, max_length=100, unique=True),
        ),
    ]
