# Generated by Django 5.2.5 on 2025-09-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiconfig', '0012_cartitem_product'),
    ]

    operations = [
    ]
